name: Sync

on: [push, pull_request]

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: gh repo sync "mayank1513/persist-and-sync" -b "main"
        env:
          GH_TOKEN: ${{ github.token }}
